server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 10Sandra10!
  jpa:
    hibernate:
      ddl-auto: update