server:
  port: 8082
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_URL}
    password: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update    
amazonProperties:
    endpointUrl: ${END_URL}
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    bucketName: ${BUCKET_NAME}
