server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Lear1007!
  jpa:
    show-sql: true
    generate-ddl: false
