server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: 27112015
  jpa:
    hibernate:
      ddl-auto: update